testing status check

diff --git a/.github/workflows/main-pipeline-dotnet.yaml b/.github/workflows/main-pipeline-dotnet.yaml
--- a/.github/workflows/main-pipeline-dotnet.yaml
+++ b/.github/workflows/main-pipeline-dotnet.yaml
@@ -40,6 +40,11 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Intentionally fail this step
+        run: |
+          echo "This step is designed to fail."
+          exit 1
+
       - name: Set up .NET
         uses: actions/setup-dotnet@v4
         with:
@@ -90,34 +95,34 @@ jobs:
           cd ${{ inputs.project-path }}  
           dotnet publish -c Release -o './published'
         
-      - name: (TEST) Upload a Build Artifact
-        uses: actions/upload-artifact@v4.6.2
-        with:
-          name: donet-artifact
-          path: "${{ inputs.project-path }}/published"
+      # - name: (TEST) Upload a Build Artifact
+      #   uses: actions/upload-artifact@v4.6.2
+      #   with:
+      #     name: donet-artifact
+      #     path: "${{ inputs.project-path }}/published"
 
-  deploy:
-    needs: build
-    runs-on: ubuntu-latest
-    environment:
-      name: ${{ inputs.project-env }}
+  # deploy:
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   environment:
+  #     name: ${{ inputs.project-env }}
 
-    steps:
-      - name: (TEST) Download Build Artifact
-        uses: actions/download-artifact@v5
-        with:
-          name: donet-artifact
+  #   steps:
+  #     - name: (TEST) Download Build Artifact
+  #       uses: actions/download-artifact@v5
+  #       with:
+  #         name: donet-artifact
 
-  cleanup:
-    runs-on: ubuntu-latest
-    needs: deploy
-    if: always()
-    steps:
-      - name: (TEST) Delete artifacts
-        run: |
-          artifacts=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts --jq '.artifacts[].id')
-          for artifact_id in $artifacts; do
-            gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$artifact_id
-          done
-        env:
-          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
+  # cleanup:
+  #   runs-on: ubuntu-latest
+  #   needs: deploy
+  #   if: always()
+  #   steps:
+  #     - name: (TEST) Delete artifacts
+  #       run: |
+  #         artifacts=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts --jq '.artifacts[].id')
+  #         for artifact_id in $artifacts; do
+  #           gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$artifact_id
+  #         done
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
